import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import { RichTextEditor } from '@/components/richTextEditor/RichTextEditor';
import { PersonData } from '@/components/PersonData/PersonData';
import { useState } from 'react';

const inter = Inter({ subsets: ['latin'] });
let rteData: string;

export default function Home() {
  const [showRTE, setShowRTE] = useState(false);
  function toggle(event: any) {
    setShowRTE(!showRTE);
    rteData = event.target.innerText;
  }

  const save = async () => {
    const res = await fetch('/api/field', {
      body: JSON.stringify({
        fieldName: 'profile',
        language: 'nl',
        value: 'Lorem ipsum',
      }),
      method: 'PUT',
    });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <PersonData />

        <div className={styles.grid}></div>
        <span onClick={event => toggle(event)}>
          click here to activate the text editor
        </span>
        <div
          style={{
            display: showRTE ? 'block' : 'none',
          }}
        >
          <RichTextEditor rteData={rteData}></RichTextEditor>
        </div>

        <button onClick={save}>Save</button>
      </main>
    </>
  );
}
